# ====== 交易所配置 ======
exchange:
  name: binance
  api_key: "YOUR_BINANCE_API_KEY"
  secret: "YOUR_BINANCE_SECRET_KEY"
  testnet: false  # 设置为 false 使用实盘
  type: "binance" # 交易所类型
  http_proxy: "http://127.0.0.1:7890"

# ====== 交易配置 ======
trading:
  # 交易对
  symbol: "DOGE/USDT:USDT"
  base_timeframe: "5m"
  leverage: 10 # 杠杆倍数
  margin_mode: "cross" # 保证金模式

# ====== 策略配置 ======
strategy:
  # 信号类型: "Open/Close" 或 "Renko"
  setup_type: "Open/Close"

  # 过滤器类型
  filter_type: "ATR and RSI"

  # 止盈止损类型: "Trailing" 或 "No"
  tps_type: "Trailing"

  # 高时间框架倍数
  htf_multiplier: 18

  # RSI参数
  rsi_period: 7
  rsi_high: 45
  rsi_low: 10

  # ATR过滤参数
  atr_filter_period: 5
  atr_filter_ma_period: 5

  # 风险管理ATR参数
  atr_risk_period: 20
  profit_factor: 2.5
  stop_factor: 10.0

  # 分批止盈设置
  enable_partial_exits: true
  tp1_factor: 1.5
  tp2_factor: 2.0
  tp1_percent: 0.5  # 第一止盈平仓50%
  tp2_percent: 0.3  # 第二止盈平仓30%

# ====== 风险管理 ======
risk_management:
  # 初始资金（USDT）
  initial_capital: 10.0  # 10 USDT

  # 仓位大小（使用资金的百分比）
  position_size: 0.95  # 使用95%资金，即9.5 USDT

  # 最大回撤限制（单笔交易）
  max_drawdown_percent: 10  # 10%

  # 每日最大亏损（USDT）
  max_daily_loss: 5.0  # 5 USDT

# ====== 订单执行配置 ======
execution:
  # 是否使用限价单（false则使用市价单）
  use_limit_orders: true

  # 订单超时时间（秒）
  order_timeout: 30

  # 限价单价格偏移（tick）
  price_tick_offset: 0.0001

  # 是否启用订单簿分析
  enable_orderbook_analysis: false

  # 最小流动性要求（USDT）
  min_liquidity: 1000

# ====== 日志配置 ======
logging:
  # 日志级别
  # 可选: DEBUG, INFO, WARNING, ERROR
  level: "DEBUG"

  # 日志文件路径
  file: "logs/live_trading_{time:YYYY-MM-DD}.log"

  # 日志轮转
  rotation: "1 day"

  # 日志保留天数
  retention: "30 days"


